version: '3.5'

services:
  db:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=test
    volumes:
      - dbdata6:/data/db

  sso:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    container_name: test-case-sso
    ports:
      - '3000:3000'
    depends_on:
      - db

  todo:
    build:
      context: ../365lab-test-case-todo
      dockerfile: Dockerfile
    environment:
      - SSO_HOST=sso
      - DB_HOST=db
    container_name: test-case-todo
    ports:
      - '3001:3001'
    depends_on:
      - db

volumes:
  dbdata6: